### ISSUE TITLE
Cannot get user info list

### ISSUE THREAD

**Issue by dearboll** [twonote/radosgw-admin4j#15]
Hi , I am running radosgw-admin4j on Ceph 10.2.7 .  What confused me is as blow.
```
List <User> users = admin.listUserInfo();   
// [{"userId":null,"displayName":null,"email":null,"suspended":null,"maxBuckets":null,"subusers":null,"s3Credentials":null,"swiftCredentials":null,"caps":null},...]
List <String> names = admin.listUser();    
//  ["registry","hr-dev","test","es","s3-dev"]

```
I can get usernames but cannot get user info . Why it happened?

**Comment by hrchu** [comment]
Hi @dearboll the problem has been fixed in the dev branch #16 . Thank you for your feedback.

If you need to use this feature from maven central instead of dev branch, please let me know. I will ship a new version to maven central ASAP.

**Comment by dearboll** [comment]
Yes, I use it via maven [https://search.maven.org/#artifactdetails%7Cio.github.twonote%7Cradosgw-admin4j%7C1.0.1%7Cjar], thank you very much!

**Comment by hrchu** [comment]
@dearboll v1.0.2 is available on maven central, check it out!

**Comment by dearboll** [comment]
Thank you very much!
