### ISSUE TITLE
the 12,2 version error

### ISSUE THREAD

**Issue by sunhy9128** [twonote/radosgw-admin4j#17]
For the 12.2.4 luminous version,the header for rgw-admin api nead a addtional header of "x-amz-content-sha256:UNSIGNED-PAYLOAD" pair? If not,with you api I alway get a "sigurnature not match" error with the correct access-secret pair.

**Comment by hrchu** [comment]
Hi @sunhy9128 

I cannot reproduce the problem you mentioned in  12.2.4 luminous. Could you give me the procedure to reproduce the problem? Thanks.

![image](https://user-images.githubusercontent.com/3183314/37012280-f6fb911a-212e-11e8-967f-4dae1f620d31.png)

**Comment by sunhy9128** [comment]
@hrchu thanks,but when i debug into the src code without any change of the test code,the problem disappeared.Now i  don't know how to reproduce this problem too...

**Comment by hrchu** [comment]
Okey. Plz let me know if you encounter any problems again.

**Comment by sunhy9128** [comment]
ok, thank you any way
