### ISSUE TITLE
cannot delete aK/sK in s3Credentials

### ISSUE THREAD

**Issue by dearboll** [twonote/radosgw-admin4j#19]
There is not a set method for me to build a S3Credential. When modify a user's aK/sK, I want to maintain only one pair of aK/sK, so I need to delete a S3Credential in the list or just build a new S3Credential. But I cannot build a S3Credential via setAk and setSk

**Comment by hrchu** [comment]
Hi could you say more about why you need to change the key pair by S3Credential setter? How about
```
rgwAdmin.removeS3Credential("userId", "keyToDelete")
rgwAdmin.createS3Credential("userId")
```

**Comment by hrchu** [comment]
@dearboll I will reopen this if you could provide more information.
