### ISSUE TITLE
individual bucket

### ISSUE THREAD

**Issue by DoTime** [twonote/radosgw-admin4j#22]
http://docs.ceph.com/docs/mimic/radosgw/adminops/#set-quota-for-an-individual-bucket

I need this, set  quota for an individual (or one by one)  bucket,  Can you give me some advise? Thanks you very much. 

    @Override
    public void setIndividualBucketQuota(String userId, String bucket, long maxObjects, long maxSizeKB) {
        setIndividualQuota(userId, bucket, "bucket", maxObjects, maxSizeKB);
    }

    //SET QUOTA FOR AN INDIVIDUAL BUCKET
    public void setIndividualQuota(String userId, String bucket, String quotaType, long maxObjects, long maxSizeKB) {
        HttpUrl.Builder urlBuilder =
                HttpUrl.parse(endpoint).newBuilder()
                        .addPathSegment("user")
                        .query("quota")
                        .addQueryParameter("uid", userId)
                        .addQueryParameter("bucket", bucket)
                        .addQueryParameter("quota-type", quotaType);

        String body = gson.toJson(ImmutableMap.of(
                "max_objects", String.valueOf(maxObjects),
                "max_size_kb", String.valueOf(maxSizeKB),
                "enabled", "true"));

        Request request = new Request.Builder().put(RequestBody.create(null, body)).url(urlBuilder.build()).build();
        safeCall(request);
    }

**Comment by libingyu** [comment]
![image](https://user-images.githubusercontent.com/15666939/56177620-d7b2e400-6031-11e9-8e9b-6b5478286ede.png)

**Comment by hrchu** [comment]
@libingyu try
```
            HttpUrl.parse(endpoint).newBuilder()
                    .addPathSegment("bucket")
                    .query("quota")
                    .addQueryParameter("uid", userId)
                    .addQueryParameter("bucket", bucket)
```

BTW would you like to send an PR for this? Thanks!

**Comment by hrchu** [comment]
ref http://tracker.ceph.com/issues/21811
@Jeegn-Chen

**Comment by libingyu** [comment]
It is work, Thanks you vury much.  You cou update radosgw-admin4j project  in the future, Thank you for your contribution , wish you a happy day.

**Comment by hrchu** [comment]
Addressed in af2bf1e

**Comment by hrchu** [comment]
@tianyale added in v1.3.0. Have a try: )

**Comment by hrchu** [comment]
It's buggy currently. https://github.com/twonote/radosgw-admin4j/commit/af2bf1e8e31db5a7dcee7a39b98c44a941ac79d4

**Comment by hrchu** [comment]
@tianyale it's fixed, and use the method name you suggested. Thanks for your comment.

* https://github.com/twonote/radosgw-admin4j/blob/master/src/main/java/org/twonote/rgwadmin4j/RgwAdmin.java#L560
* https://github.com/twonote/radosgw-admin4j/blob/master/src/main/java/org/twonote/rgwadmin4j/impl/RgwAdminImpl.java#L761
* https://github.com/twonote/radosgw-admin4j/blob/master/src/test/java/org/twonote/rgwadmin4j/impl/RgwAdminImplTest.java#L945

Feel free to provide more comment and PRs, thanks!
