### ISSUE TITLE
I can not change subuser permission with setSubUserPermission

### ISSUE THREAD

**Issue by swimfish09** [twonote/radosgw-admin4j#23]
```
List<SubUser> list = rgwAdmin.setSubUserPermission("test", "subtest", Permission.READ_WRITE);
POST /admin/user?subuser&uid=test&subuser=subtest&access=read_write
```
not read_write but readwrite

**Comment by swimfish09** [comment]
#https://github.com/twonote/radosgw-admin4j/pull/24

**Comment by hrchu** [comment]
Nice catch, thanks for your that!

**Comment by hrchu** [comment]
Hi @swimfish09 ,
I notice that your email in this PR is "liangsibin at 189.cn" which is not set it in your Github profile.
It will be better to link this email with your Github account, so GitHub can count your contributions.

Add your email on https://github.com/settings/emails
