### ISSUE TITLE
Excuse， I want to ask a question, if ceph can't create a bucket named admin.

### ISSUE THREAD

**Issue by zjylx** [twonote/radosgw-admin4j#25]
In ceph docs , I found nothing about this. 
but because the radosgw-admin's rest api use /admin/ , so I can't create a bucket named admin in the blank tenant.

**Comment by hrchu** [comment]
Okay, you have few options: 
1. Prevent using a bucket named ``admin``
2. Adjust radowgw config: ``rgw admin entry``. Ref more here: https://docs.ceph.com/docs/giant/radosgw/config-ref/

**Comment by zjylx** [comment]
@hrchu OK, thank you
