### ISSUE TITLE
how to  create a bucket ?

### ISSUE THREAD

**Issue by fallowu** [twonote/radosgw-admin4j#34]
just find to get bucket info ,no create bucket api by using RGW_ADMIN.

**Comment by hrchu** [comment]
Hi @fallowu,
`create bucket` is an S3 API. However, this is a radowgw **admin** library. 

If what you want are S3 APIs, you should use https://github.com/aws/aws-sdk-java instead.

Here is an usage example: https://github.com/twonote/radosgw-admin4j/blob/master/src/test/java/org/twonote/rgwadmin4j/examples/Example.java#L61
