### ISSUE TITLE
Optional.empty and 404

### ISSUE THREAD

**Issue by psharaev** [twonote/radosgw-admin4j#52]
I am very concerned about the following method
```java
private String safeCall(Request request) {
  try (Response response = client.newCall(request).execute()) {
    if (response.code() == 404) {
      return null;
    }
    if (!response.isSuccessful()) {
      throw ErrorUtils.parseError(response);
    }
    ResponseBody body = response.body();
    if (body != null) {
      return response.body().string();
    } else {
      return null;
    }
  } catch (IOException e) {
    throw new RgwAdminException(500, "IOException", e);
  }
}
```

This does not distinguish between a 404 situation and a null body, since in these two cases null is returned, which overwrites the cause. I want to draw attention to the fact that all other errors are thrown, for example, 403. This is important for future examples.

What causes the problem with all methods to grow.

```java
@Override
public Optional<User> getUserInfo(String userId) {
  HttpUrl.Builder urlBuilder =
      HttpUrl.parse(endpoint)
          .newBuilder()
          .addPathSegment("user")
          .addQueryParameter("uid", userId);

  Request request = new Request.Builder().get().url(urlBuilder.build()).build();

  String resp = safeCall(request);
  return Optional.ofNullable(gson.fromJson(resp, User.class));
}
```

How will I use this method then:
```java
RgwAdminImpl admin = new RgwAdminImpl("access", "secret", "endpoint");

try {
  User user =
      admin.getUserInfo("id")
              .orElseThrow(() -> new NoSuchElementException("not found (404)"));
} catch (RgwAdminException | NoSuchElementException e) {
  System.err.println("error logic: " + e.getMessage());
}
```
I still need a try catch to handle errors, and write `orElseThrow` for some reason. But it's actually confusing. `Optional<User>` when empty, it does not mean that this is normal behavior, it is just a ignored error

But the worst thing happens in the following example. It is simply impossible to write code here, either to throw an exception, or no policy has really been set.
```java
try {
  admin.getBucketPolicy("bucet_name")
              .orElseThrow(() -> new NoSuchElementException("not found (404), or incorrect bucket name?"));
} catch (RgwAdminException | NoSuchElementException e) {
  System.err.println("error logic: " + e.getMessage());
}
```

I really want to fix this, but I absolutely do not know for which methods `Optional.empty` is normal behavior, and for which it is a ignored error

**Comment by psharaev** [comment]
This can be easily fixed. But other methods also need to be corrected where it is `Optional.empty` meant implicitly 404 or also additionally that this is normal behavior that the body is null
```java
private Optional<String> safeCall(Request request) {
  try (Response response = client.newCall(request).execute()) {
    if (!response.isSuccessful()) {
      throw ErrorUtils.parseError(response);
    }
    ResponseBody body = response.body();
    if (body != null) {
      return Optional.of(response.body().string());
    } else {
      return Optional.empty();
    }
  } catch (IOException e) {
    throw new RgwAdminException(500, "IOException", e);
  }
}
```

**Comment by psharaev** [comment]
Well, perhaps this solution will suit me, thank you!

**Comment by hrchu** [comment]
Feel free to discuss and share your usage experience anytime!
